### PR TITLE
Feature/turborepo

### PR DESCRIPTION
**Pull request by kuntik17**
Replaced Lerna with Turbo and added Docker file to create image from local setup.

### CODE REVIEW

**Comment by kuntik17** [comment]
See turborepo in action... yarn -> yarn build -> yarn dev

https://www.loom.com/share/c2b81f5ec4ac446a88e2a92fea6e923f

Console errors and warning caused by my custom nodes, which i didn't put my PR..

**Comment by HenryHengZJ** [comment]
@kuntik17 can you also update `main.yml` file? line 30 onwards

**Comment by kuntik17** [comment]
@HenryHengZJ which yml file?

**Comment by HenryHengZJ** [comment]
@kuntik17 can you allow permission for me to edit your forked repo? I have a few more changes I would like to add

Here's the [doc](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by jjohnson5253** [comment]
Any updates on this @HenryHengZJ? Anything I can help with?

**Review by HenryHengZJ — APPROVED** [review]
thanks @jjohnson5253 and @kuntik17 for this!

**Pull request merged**
