### PR TITLE
Chores/eslint prettier for component and server

### PR DESCRIPTION
**Pull request by tylim88**
1. removing all lock file before bootstrap seem to ensure symlink
2. also removed @type/nodes
3. refactor gitignore, eslint, prettier, common dev dependencies to root
4. resolve any dependency that is different from the hoisted

run `yarn bootstrap` first because eslint is updated to v8, after that you can try run `yarn lint` or `yarn lint-fix` in root to see the effect

see commit messages for more details

### CODE REVIEW

**Comment by tylim88** [comment]
it is also possible to refactor tsconfig, but I will do that after i complete the ui conversion

**Comment by tylim88** [comment]
this commit https://github.com/Outerbridgeio/Outerbridge/pull/98/commits/6e4fc53e916a7f817cc2d6bd2dc6dd112cdb9bd1 will make prettier remove all semi colon of most cases when you run lint-fix

prettier will insert semicolon automatically if the statement start with `[` to void mistake https://prettier.io/docs/en/rationale.html#semicolons

**Comment by tylim88** [comment]
1. now there is only one gitignore, prettierignore, eslint config, prettier config, all in the root folder
2. commit hook added (lint and format)
3. formatted all files at https://github.com/Outerbridgeio/Outerbridge/pull/98/commits/a17b7bf44cf611604459596077a14f648bca2c25

**Comment by tylim88** [comment]
changes that need manual test
https://github.com/Outerbridgeio/Outerbridge/pull/98/commits/16f3393bc844023ed08ad3ac5f08fc3ba7dfe765
https://github.com/Outerbridgeio/Outerbridge/pull/98/commits/2ec782d93d9f6c8f31d22e933abc9d8b158e32f9
https://github.com/Outerbridgeio/Outerbridge/pull/98/commits/83f848ccf42d24026f067b08a972c13cb2d613ec
https://github.com/Outerbridgeio/Outerbridge/pull/98/commits/d1978c72c038024eaa1e097752378d84c34fb5e3

**Comment by tylim88** [comment]
website seem fine, but I need your help to test these commit @HenryHengZJ 

> changes that need manual test [16f3393](https://github.com/Outerbridgeio/Outerbridge/commit/16f3393bc844023ed08ad3ac5f08fc3ba7dfe765) [2ec782d](https://github.com/Outerbridgeio/Outerbridge/commit/2ec782d93d9f6c8f31d22e933abc9d8b158e32f9) [83f848c](https://github.com/Outerbridgeio/Outerbridge/commit/83f848ccf42d24026f067b08a972c13cb2d613ec) [d1978c7](https://github.com/Outerbridgeio/Outerbridge/commit/d1978c72c038024eaa1e097752378d84c34fb5e3) [a973b23](https://github.com/Outerbridgeio/Outerbridge/commit/a973b230e95f93cd5a308160d7e1f811c8207a6b)

**Comment by tylim88** [comment]
nothing to add now

one weird thing is, react-scripts will fail the compilation in CI if it has `no-console` eslint warning

**Comment by tylim88** [comment]
basically that is it

in nodejs 16, you should not see any warning when you run bootstrap, build, lint, start and dev
in nodejs 14 however, you will see warnings when you run lint, eslint think typescript type is some kind of variable

**Review by HenryHengZJ — APPROVED** [review]
All looks good! merging it

**Pull request merged**
