### PR TITLE
Bugfix: Change HTML text in information icons to plain text

### PR DESCRIPTION
**Pull request by affanmustafa**
Issue #81

### CODE REVIEW

**Review by HenryHengZJ — APPROVED** [review]
looks good! @affanmustafa if you can sign the CLA thanks!

**Comment by affanmustafa** [comment]
@HenryHengZJ Done. Could you also kindly mark this with Hacktoberfest accepted tag?

**Comment by HenryHengZJ** [comment]
Hey @affanmustafa I jumped into conclusion too quickly sorry :( 

I actually found out its better to render the HTML tag.

So replacing `<Tooltip title={input.description}` to `<Tooltip title={<div dangerouslySetInnerHTML={{ __html: input.description}}/>}` will actually render the HTML:

image.

Would you be able to replace all occurrence?

**Comment by tylim88** [comment]
wait, please check this solution first, using https://www.npmjs.com/package/html-react-parser

https://github.com/Outerbridgeio/Outerbridge/pull/85/commits/dd8a30abf5393069c947df610f0d435f5b13b46f#diff-ba80e49ed616bd634a934d0fd5b8fd0686434126dd86bfe29bced2dfeccc801d

**Comment by HenryHengZJ** [comment]
@tylim88 yeah I think this is better as the library can handle sql injection which can be possibly introduced using dangerouslySetInnerHTML. Do you mind to have @affanmustafa work towards this direction, so we can keep the bugfix here and telegram pr seperately. Thanks for the suggestion @tylim88 !

**Comment by tylim88** [comment]
ok 👍

**Pull request closed without merging**
